version: 2

models:
  - name: stg_session
    description: "Staging model for session data"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
        - unique
        - not_null

      - name: playerId
        description: "The ID of the player associated with the session"
        data_tests:
        - not_null
        - relationships:
            arguments:
              to: ref("stg_players")
              field: id

      - name: accuracy
        description: "Players typing accuracy"
        data_tests:
        - not_null

      - name: wpm
        description: "Players word per minute"
        data_tests:
        - not_null

      - name: createdAt
        description: "When the game was played"
        data_tests:
        - not_null

      - name: score
        description: "Final score (accuracy and wpm combined)"
        data_tests:
        - not_null

      - name: daily
        description: "Was the game daily game or normal game"
        data_tests:
        - not_null
        #  - accepted_values:
        #      arguments:
        #        values: [true, false]
        # issue with this for some reason ^
        # otherwise all the tests worked without issues
  
  - name: stg_players
    description: "Staging for player data"
    columns:
    - name: id
      description: "PlayerId"
      data_tests:
      - unique
      - not_null

    - name: username
      description: "Users unique username"
      data_tests:
      - unique
      - not_null

    - name: createdAt
      description: "When was the user created"
      data_tests:
      - not_null
