version: 2

models:
  - name: stg_session
    description: "Staging model for session data"
    columns:
      - name: session_id
        description: "The primary key for this table"
        data_tests:
        - unique
        - not_null

      - name: playerId
        description: "The ID of the player associated with the session"
        data_tests:
        - not_null
        - relationships:
            arguments:
              to: ref("stg_players")
              field: player_id

      - name: accuracy
        description: "Players typing accuracy"
        data_tests:
        - not_null

      - name: wpm
        description: "Players word per minute"
        data_tests:
        - not_null

      - name: createdAt
        description: "When the game was played"
        data_tests:
        - not_null

      - name: score
        description: "Final score (accuracy and wpm combined)"
        data_tests:
        - not_null

      - name: daily
        description: "Was the game daily game or normal game"
        data_tests:
        - not_null
        #  - accepted_values:
        #      arguments:
        #        values: [true, false]
        # issue with this for some reason ^
        # otherwise all the tests worked without issues
  
  - name: stg_players
    description: "Staging for player data"
    columns:
    - name: player_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null

    - name: username
      description: "Users unique username"
      data_tests:
      - unique
      - not_null

    - name: createdAt
      description: "When was the user created"
      data_tests:
      - not_null

  - name: stg_sentence
    description: "Staging for sentence data"
    columns:
    - name: sentence_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null

    - name: text
      description: "Sentence that the player writes during the game"
      data_tests:
      - unique
      - not_null

    - name: createdAt
      description: "When was the sentence created"
      data_tests:
      - not_null

  - name: stg_dailychallenge
    description: "Staging for dailychallenge data"
    columns:
    - name: daily_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null

    - name: date
      description: "What days daily challenge it is"
      data_tests:
      - unique
      - not_null

    - name: text
      description: "Sentence for daily challenge which is gotten from sentence table"
      data_tests:
      - not_null

    - name: createdAt
      description: "When the dailychallenge was added"
      data_tests:
      - not_null